### ISSUE TITLE
that was a truly pleasing experience

### ISSUE THREAD

**Issue by frdnrdb** [amiechen/codrops-scribbler#1]
thanks!

this is not really an issue; i just noticed you gave up on line 95 in the script .-)
here's a simple way to keep that i-value in the loop: https://jsfiddle.net/xq3eLLjq/

**Comment by amiechen** [comment]
Awesome -- thank you for pointing it out and I completely forgot I did that 😅! I've updated the code with your solution. Thank you so much!
